<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MelbergFramework.Infrastructure.Redis\MelbergFramework.Infrastructure.Redis.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MelbergFramework.Core.ComponentTesting" Version="8.0.10" />
    <PackageReference Include="Testcontainers.Redis" Version="4.10.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
  </ItemGroup>

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Version>1.0.2</Version>
		<Authors>Joseph Melberg</Authors>
        <PackageId>MelbergFramework.ComponentTesting.Redis</PackageId>
		<ImplicitUsings>enable</ImplicitUsings>
		<IsPackable>true</IsPackable>
		<Nullable>enable</Nullable>
		<PackageLicenseExpression>GPL-3.0-only</PackageLicenseExpression>
	</PropertyGroup>
</Project>
